_select_data:

_inputs:
  map:
    comment: "Update the map location and display settings."
  latitude:
    comment: "Coordinates for the center marker on the map."
  longitude:
    comment: "Coordinates for the center marker on the map."
  zoom:
    comment: "The zoom level for the map."
  pricing_table:
    comment: "Update the information in the pricing tables."
  highlight:
    comment: "Emphasis the text"
  color:
    comment: "The background color used in the plan name and call to action."
  new_window:
    comment: "Open link in new window"
  description:
    comment: ""
source_editor:
    tab_size: 2
    show_gutter: false
    theme: pastel_on_dark
collections_config:
  pages:
    path: content
    name: Pages
    icon: wysiwyg
  coordinators:
    path: _coordinators
    name: Coordinators
    _enabled_editors:
      - visual
      - data
      - content
    icon: account_circle
  booths:
    _enabled_editors:
      - data
      - content
      - visual
    icon: photo_camera
  event_type:
    _enabled_editors:
     - data
     - content
     - visual
    icon: event
  products:
    _enabled_editors:
      - data
      - content
      - visual
    output: true
    icon: shopping_cart
    schemas:
      default:
        path: schemas/products.md
_enabled_editors:
        - data
        - content
        - visual
_editables:
        content:
          bold: true
          italics: true
          underline: true
editor:
  default_path: /en/
source_editor:
  tab_size: 2
  show_gutter: false
  theme: pastel_on_dark
timezone: CDT
commit_templates:
  - template_string: '{message}'
markdown:
  engine: markdown
