_select_data:

_inputs:
  map:
    comment: "Update the map location and display settings."
  latitude:
    comment: "Coordinates for the center marker on the map."
  longitude:
    comment: "Coordinates for the center marker on the map."
  zoom:
    comment: "The zoom level for the map."
  pricing_table:
    comment: "Update the information in the pricing tables."
  highlight:
    comment: "Emphasis the text"
  color:
    comment: "The background color used in the plan name and call to action."
  new_window:
    comment: "Open link in new window"
  description:
    comment: ""
source_editor:
    tab_size: 2
    show_gutter: false
    theme: pastel_on_dark
collections_config:
  staff_members:
    _enabled_editors:
      - data
      - content
      - visual
    icon: account_circle
    schemas:
      default:
        path: schemas/staff_members.md
  coordinators:
    _enabled_editors:
      - data
      - content
      - visual
    icon: account_circle
  booths:
    _enabled_editors:
      - data
      - content
      - visual
    icon: photo_camera
  event_type:
    _enabled_editors:
     - data
     - content
     - visual
    icon: event
  products:
    _enabled_editors:
      - data
      - content
      - visual
    output: true
    icon: shopping_cart
    schemas:
      default:
        path: schemas/products.md
